name: test

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.*"

  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout source files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
          cache: 'pip'
          cache-dependency-path: 'setup.cfg'

      - name: Install Python dependencies
        run: pip install .[dev]

      - name: Run PyTest
        run: pytest --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          name: codecov-evotorch
          verbose: true
